export class ProfilePagesConstants {
  static readonly attributes = Object.freeze({
    classes: {
      userLocation: 'user-location',
      userTimeZone: 'user-timezone',
      candidateInfoHeader: 'candidate-info-header',
      phone: 'candidate-phone',
      email: 'candidate-email',
      linkedIn: 'candidate-linkedin',
      resume: 'candidate-resume',
      takeTourDialogTitle: 'tutorial-title',
      button: 'action-button',
      roleColumn: 'role-column',
      statusColumn: 'status-column',
      bfqColumn: 'bfq-column',
      skillBadges: 'SkillBadges',
      header: 'headline',
      candidateTimeline: 'candidate-timeline-header',
      candidateTimelineDescription: 'timeline-info-details-description',
      timelineDate: 'timeline-info-details-date',
      newBadge: 'new-badge',
      badgesHeadline: 'badges-headline',
      infoHeader: 'information-headline',
      addSectionButton: 'add-section-button',
      sectionMenuItem: 'section-menu-item',
      sectionMenu: 'section-menu',
      matButton: 'mat-button',
      pipelineName: 'pipeline-name',
      applicationStatus: 'ApplicationStatus',
      failedNotification: 'snackbar-profile-error',
      badgeIcon: 'badge-icon',
      activeBadge: 'white',
      notActiveBadge: 'gray',
      warningNotification: 'snackbar-profile-warning',
      badgeName: 'badge-name',
      activeStar: 'fas fa-star star',
      inactiveStar: 'far fa-star star-border',
      retryBadge: 'yellow',
      successBadge: 'green',
      successNotification: 'snackbar-profile-success',
      startButton: 'start-button',
      actionButton: 'action-button',
      skillColumn: 'progress-column',
      applicationHeader: 'application dropdown-toggle',
      otherApplication: 'other-applications',
      dialogContainer: 'mat-dialog-container',
      headerContent: 'header-content',
      introduction: 'introduction',
      companyTitle: 'title',
      workExpDescription: 'record-type__desc',
      actionButtons: 'action-buttons',
      failedZeroStarNotification: 'snackbar-profile-zerostars',
    },
    formControlName: {
      description: 'Description',
      title: 'What__c',
      company: 'Institution__c',
      currentJob: 'Ongoing__c',
      workExpDescription: 'Description__c',
      companyUrl: 'URL__c',
      degree: 'Degree__c',
      grade: 'Grade__c',
      associatedWith: 'Associated_with__c',
      credentialId: 'ExternalId__c',
    },
  });

  static readonly elementNames = Object.freeze({
    userLocation: 'User Location',
    userTimeZone: 'User Timezone',
    candidateInfoHeader: 'Candidate Information',
    phone: 'Phone number',
    email: 'Email',
    linkedIn: 'LinkedIn',
    resume: 'Resume',
    takeTourTitle: 'Welcome to your new Crossover Profile!',
    takeTour: 'TAKE TOUR',
    followRecommendation: 'Follow recommendations to fast track your Application',
    next: 'NEXT',
    finish: 'FINISH',
    followProgress: 'Follow progress of your applications',
    myApplication: 'My application',
    myProfile: 'My profile',
    jobApplication: 'Job Applications',
    role: 'Role',
    basicFit: 'Basic Fit',
    requiredSkill: 'Required Skill Badges',
    requiredRealWork: 'Required Real Work Badges',
    status: 'Status / Next Step',
    candidateTimeline: 'Candidate Timeline',
    appliedFor: 'Applied for',
    createAccount: 'Created Account on Crossover',
    skillBadge: 'Skills Badges',
    realWorkBadge: 'RealWork Badges',
    introduction: 'Introduction',
    workExperience: 'Work Experience',
    education: 'Education',
    introduceYourself: 'Introduce yourself',
    addWorkExp: 'Add Work Experience',
    addEduction: 'Add Education',
    addSection: 'Add Section',
    award: 'Award',
    certification: 'Certification',
    patent: 'Patent',
    publication: 'Publication',
    sectionMenu: 'Section Menu',
    pipelineName: 'Pipeline Name/ Role Name',
    recommendedJobs: 'Recommended Jobs',
    statusNextStep: 'Status / Next Step',
    failedMessage: 'The minimum required by',
    cognitiveWarningNotification: "You've earned the ★★✰✰✰ Cognitive Aptitude badge",
    cognitiveSuccessNotification: "You've earned the ★★★✰✰ Cognitive Aptitude badge",
    earnThisBadge: 'LEARN MORE',
    start: 'START',
    takeTheTest: 'TAKE THE TEST',
    notSupportedBrowser: 'Your browser is not supported',
    switchUIMessage: 'This application must be viewed in our old app',
    applicationFor: 'Application for',
    otherApplication: 'Other Application',
    addIntroduction: 'Add Introduction',
    save: 'SAVE',
    startDateFormat: 'YYYY-MM-DD',
    addAwards: 'Add Awards',
  });
}
