export class CatalogConstants {
  static readonly attributes = Object.freeze({
    classes: {
      domainName: 'domain-name',
      catalogHeader: 'header',
      categoryName: 'category-name',
      availableBadgeHeader: 'available-badge-header',
      profileLink: 'profile-link',
      badgeName: 'badge-name',
      badgeCard: 'badge-card',
      badgeDetailCard: 'badge-details-container',
      badgeDetailHeader: 'badge-detail-header',
      startButton: 'start-button',
      noBadge: 'warning-box-text',
      starsContainer: 'stars-container',
      earnedStar: 'fas fa-star',
      appBadgeCard: 'app-badge-card',
      expandedDetails: 'badge-details-expanded',
      lockedReason: 'locked-pipelines-suggestion__text',
      suggestionLink: 'suggestion-link',
      lockedReasonAlert: 'locked-reason-modal',
      dialog: 'mat-dialog-container',
      lockedReasonHeader: 'locked-reason-modal__header',
      button: 'mat-button',
      badgeDetailCloseButton: 'badge-detail-close',
    },
  });

  static readonly elementNames = Object.freeze({
    skillCatalog: 'Skills Badge Catalog',
    backToMyProfile: 'Back to my profile',
    psychoCognitive: 'Psychocognitive',
    language: 'Language',
    technical: 'Technical',
    support: 'Support',
    finance: 'Finance',
    sales: 'Sales',
    management: 'Management',
    cognitiveAbility: 'Cognitive',
    cognitiveAptitude: 'Cognitive Aptitude',
    earThisBadge: 'Earn this badge',
    start: 'START',
    realWorkCatalog: 'RealWork Badge Catalog',
    noBadge: 'No badges found',
    learn: 'Learn and Explain New Products',
    objectHandling: 'Objection Handling',
    pipelineDependency:
      'To unlock this badge you need to apply to a role that requires it and reach the necessary level of testing.',
    stageDependency: 'To unlock this badge you need to reach the stage of testing on the roles that require it',
    clickHere: 'Click here',
    written: 'Written Communication Skills',
    badgeDependency: 'This badge requires taking other badges first',
    clickToSee: 'check to see what badges are',
  });
}
